### ISSUE TITLE
Color pallet for the theme color and secondary theme color not fully displayed

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/gilb-theme#1]
The color pallet for the theme color and secondary theme color are not fully displayed : 
https://prnt.sc/uqvwge
https://prnt.sc/uqvwiy

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
