### ISSUE TITLE
Header Color Section , color pallet not fully displayed

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/gilb-theme#3]
The Header Color section does not displays the full color pallets for the following elements : 
Dropdown menu BG color : https://prnt.sc/uqvzsq
Dropdown menu color : https://prnt.sc/uqvzzu
Dropdown menu hover color : https://prnt.sc/uqw05d

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
